spring:
  profiles:
    active: dev
  # disable web handler #
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

  ### data source ###
  datasource:
    url: jdbc:mysql://172.20.127.88:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
    username: dev
    password: Seaso@2019
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### jpa ###
  jpa:
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.auto: update
  jackson:
    serialization.indent-output: true
    time-zone: GMT+8

### ID generator ###
idgen:
  machine-id: 0
  data-center-id: 0
  cache: 1024

data:
  elasticsearch:
    cluster-name: #默认为elasticsearch
    cluster-nodes: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
    properties:
      path:
        logs: ./elasticsearch/log #elasticsearch日志存储目录
        data: ./elasticsearch/data #elasticsearch数据存储目录

