spring:
  profiles:
    active: dev
  # disable web handler #
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

  ### data source ###
  datasource:
    url: jdbc:mysql://172.20.127.88:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: dev
    password: Seaso@2019
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### jpa ###
  jpa:
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.auto: update
  jackson:
    serialization.indent-output: true

### logging ###
logging:
  file: log/spring.log

### ID generator ###
idgen:
  machine-id: 0
  data-center-id: 0
