server:
  port: 8080

spring:
  profiles:
    active: dev
  # disable config handler #
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

  data:
    elasticsearch:
      cluster-name: seaso
      cluster-nodes: localhost:9300

  ### data source ###
  datasource:
    url: jdbc:mysql://172.20.127.88:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
    username: dev
    password: Seaso@2019
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### jpa ###
  jpa:
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.auto: update
  jackson:
    serialization.indent-output: true
    time-zone: GMT+8

### ID generator ###
idgen:
  machine-id: 0
  data-center-id: 0
  cache: 1024

### model server ###
model-server:
  address: localhost
  port: 5000
